#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-unf_ext
Version  : 0.0.7.1
Release  : 3
URL      : https://rubygems.org/downloads/unf_ext-0.0.7.1.gem
Source0  : https://rubygems.org/downloads/unf_ext-0.0.7.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-unf_ext-lib
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rake
BuildRequires : rubygem-rake-compiler
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-test-unit

%description
ruby-unf_ext
============
Synopsis
--------
* Unicode Normalization Form support library for CRuby

%package lib
Summary: lib components for the rubygem-unf_ext package.
Group: Libraries

%description lib
lib components for the rubygem-unf_ext package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n unf_ext-0.0.7.1
gem spec %{SOURCE0} -l --ruby > rubygem-unf_ext.gemspec

%build
gem build rubygem-unf_ext.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
unf_ext-0.0.7.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/unf_ext-0.0.7.1
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/unf_ext-0.0.7.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/unf_ext-0.0.7.1/ri/UNF/Normalizer/cdesc-Normalizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/unf_ext-0.0.7.1/ri/UNF/cdesc-UNF.ri
/usr/lib64/ruby/gems/2.2.0/doc/unf_ext-0.0.7.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/unf_ext-0.0.7.1/ri/ext/unf_ext/page-Makefile.ri
/usr/lib64/ruby/gems/2.2.0/doc/unf_ext-0.0.7.1/ri/page-LICENSE_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/unf_ext-0.0.7.1/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/unf_ext-0.0.7.1/gem.build_complete
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/unf_ext-0.0.7.1/gem_make.out
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/unf_ext-0.0.7.1/mkmf.log
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/.document
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/Gemfile.lock
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/ext/unf_ext/.RUBYARCHDIR.time
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/ext/unf_ext/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/ext/unf_ext/extconf.rb
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/ext/unf_ext/unf.cc
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/ext/unf_ext/unf.o
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/ext/unf_ext/unf/normalizer.hh
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/ext/unf_ext/unf/table.hh
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/ext/unf_ext/unf/trie/char_stream.hh
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/ext/unf_ext/unf/trie/node.hh
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/ext/unf_ext/unf/trie/searcher.hh
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/ext/unf_ext/unf/util.hh
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/lib/unf_ext.rb
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/lib/unf_ext/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/test/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/test/normalization-test.txt
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/test/test_unf_ext.rb
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/unf_ext.gemspec
/usr/lib64/ruby/gems/2.2.0/specifications/unf_ext-0.0.7.1.gemspec

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/unf_ext-0.0.7.1/unf_ext.so
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/ext/unf_ext/unf_ext.so
/usr/lib64/ruby/gems/2.2.0/gems/unf_ext-0.0.7.1/lib/unf_ext.so
